---
- name: Installation of nginx without handler
  hosts: all
  become: true
  tasks:
    - name: Install nginx
      yum:
           name: nginx
           state: present
    - name: Nginx services start
      service:
          name: nginx
          state: started


